# 应用名称
spring:
  application:
    name: jwt-spring-boot-starter

jwt:
  # 可选，默认配置：custom-jwt
  id: jwt-test
  # 长度64
  base64Secret: PnJ7gvAwryqKlUQeokI19aXN3fpz6c2tPnJ7gvAwryqKlUQeokI19aXN3fpz6c2t
  # 可选，默认 HS256，可选：HS256、HS384、HS512
  mac: HS256
  # 可选，默认配置：3600，单位：秒
  expiresSecond: 3600
